version: '3.7'

services:
  landing:
    image: "landing"
    container_name: "mvbureev-landing"
    build:
      dockerfile: "Dockerfile"
      context: "./"
      cache_from:
      - "landing"
    restart: "unless-stopped"
    ports:
      - "3001:3000"
    environment:
      - "VIRTUAL_HOST=mvbureev.ru,www.mvbureev.ru"
      - "LETSENCRYPT_HOST=mvbureev.ru,www.mvbureev.ru"
    networks:
      - "mvbureev-network"

networks:
  mvbureev-network:
    external: true

volumes:
  landing:
